{{- if .Values.web.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontdesk.web.serviceAccountName" . }}
  labels:
    {{- include "frontdesk.web.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if .Values.api.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontdesk.api.serviceAccountName" . }}
  labels:
    {{- include "frontdesk.api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automountServiceAccountToken }}
{{- end }}
