{{- if .Values.web.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontdesk.web.serviceAccountName" . }}
  labels:
    {{- include "frontdesk.web.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automountServiceAccountToken }}
{{- end }}
