---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: frontdesk
spec:
  encryptedData:
    auth-secret: AgBeqO78HZkmynFcKh9a/LGVYvRJ0TzKTdvq4BUzAAwZ+otEsnYsxYPJwWEFkrBPO+/+WzJJNqQpcfeoII4dIVAprCGMMy+3HMOT89pPV6tCwWRc4JyvJyyJgRU7D7Una148lcFbKQEYCxr8U1Ta+zUfyEIqoXOUVwE9/irJCGgrFIPph4JS6U/+0J1epfc33212hTiboREh/HH94PFAygxAZg9ElPIRdq3i3Stpf66oZ8RYsJUZNMU9KJPvaoeann7MhDUkTUnYabOfXHtxFou58mqIzTaCzGcHxrOxtTNQooK3hGjaKr9Bdber19k3ePunxyV1/uiGrt4twcQuLj8vYRQ3GHtB0wyn/4RGFhZGfq+Pryl4xJ4lS2finZ8LVZ+oa6+tMXKxCNBinAsClY+GxLP7fh0ckkmbntbi4ec5RockgnNSGAqvrPCUNgS30hbmzfE69iiUguKKJfgmuw2N9JWP8KwuBLAoezvy7Arx9rCZbzwL2ddVNQ4cE/Eu9vseAMVkIbso1hLpaB5aEfUvagcXCNJ69Lvsn9/DUZshFFB0YcE9Z91tsvvfsZNP/KUEMmQBkCQ4B9GMcrzFwZJD1WEXtWZqbYBwpr1evAgminWfPDS0Qknu2LFAqKyfW8g8rlWTyA/3vOO+JcfFp33z6bX+n8LM+8EBk2WTVzDCh+sUgdzIV2gOu3XTflWDpWAVwE7WsHDMmqUGxPPPqJFovJnAJAHFp6nPOoeid76uOhRAnfKponCPY/N3cg==
  template:
    metadata:
      name: auth-secret
      namespace: frontdesk
